app = 'ymax-poc-ui'
primary_region = 'ord'
console_command = '/bin/bash'

[[domains]]
  name = 'ymax.app'

[build]

[env]
  NODE_ENV = 'production'

[deploy]
  strategy = 'rolling'
  max_unavailable = 1

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = 'suspend'
  auto_start_machines = true
  min_machines_running = 1
  processes = ['app']

[[services]]
  protocol = 'tcp'
  internal_port = 3000
  processes = ['app']

  [[services.ports]]
    port = 80
    handlers = ['http']
    force_https = true

  [[services.ports]]
    port = 443
    handlers = ['tls', 'http']

  [services.concurrency]
    type = 'connections'
    hard_limit = 25
    soft_limit = 20

  [[services.tcp_checks]]
    interval = '30s'
    timeout = '10s'
    grace_period = '30s'
    restart_limit = 3

  [[services.http_checks]]
    interval = '30s'
    timeout = '10s'
    grace_period = '30s'
    method = 'GET'
    path = '/health'
    protocol = 'http'
    tls_skip_verify = false
    restart_limit = 3

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1