app = 'ymax-poc-ui'
primary_region = 'ord'
console_command = '/bin/bash'

[[domains]]
  name = 'ymax.app'

[build]

[env]
  NODE_ENV = 'production'

[deploy]
  strategy = 'rolling'
  max_unavailable = 1

[[services]]
  protocol = 'tcp'
  internal_port = 3000
  processes = ['app']

  [[services.ports]]
    port = 80
    handlers = ['http']
    force_https = true

  [[services.ports]]
    port = 443
    handlers = ['tls', 'http']

  [services.concurrency]
    type = 'connections'
    hard_limit = 25
    soft_limit = 20

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1